base/urls.py
from django.urls import path
from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate, TaskDelete, CustomLoginView, RegisterPage
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy
from . import views
app_name = 'base'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/',views.logout, name='logout'),
    path('register/', RegisterPage.as_view(), name='register'),
    
    path('', TaskList.as_view(), name='tasks'),
    path('task/<int:pk>/', TaskDetail.as_view(), name='task'),
    path('task-create', TaskCreate.as_view(), name='task-create'),
    path('task-update/<int:pk>/', TaskUpdate.as_view(), name='task-update'),
    path('task-delete/<int:pk>/', TaskDelete.as_view(), name='task-delete'),
]

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    create = models.DateTimeField(auto_now_add=True)

def __str__(self):
    return self.title

class Meta():
    ordering = ['complete']

base/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

from django.urls import reverse_lazy, reverse
from .models import Task

class CustomLoginView(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('base:tasks')
    
def logout(request):
    render(request, "base/logout.html")
    return HttpResponseRedirect(reverse('base:login'))

class RegisterPage(FormView):
    template_name = 'base/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('base:tasks')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('base:tasks')
        return super(RegisterPage, self).get(*args, **kwargs)


class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        context['count'] = context['tasks'].filter(complete=False).count()

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(title__startswith=search_input)

        context['search-input'] = search_input
        
        return context


class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'base/task.html'

class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['title', 'description']
    success_url = reverse_lazy('base:tasks')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)

class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title', 'description', 'complete']
    success_url = reverse_lazy('base:tasks')

class TaskDelete(DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('base:tasks')

base/templates/base/login.html
{% extends 'base/main.html' %}
{% block content %}
<div class="header-bar">
    <h1>Login</h1>
</div>
<div class="card-body">
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input class="button" type="submit" value="Login">
</form>
<p>Don't have an Account ? <a href="{% url 'base:register' %}">Register</a></p>
{% endblock %}
</div>

base/templates/base/logout.html
<form method="POST" action="{% url 'base:logout' %}">
    {% csrf_token %}
    <button type="submit">logout</button>
</form>

base/templates/base/main.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>To Do List</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="{% static 'base/main.css' %}">
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

base/templates/base/register.html
{% extends 'base/main.html' %}
{% block content %}

<div class="header-bar">
    <h1>Register</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <label>{{form.username.label}}</label>
        {{form.username}}

        <label>{{form.password1.label}}</label>
        {{form.password1}}

        <label>{{form.password2.label}}</label>
        {{form.password2}}
        <input style="margin-top:10px ;" class="button" type="submit" value="Register">
    </form>
    <p>Already have an account? <a href="{% url 'base:login' %}">Login</a></p>
</div>




{% endblock content %}

base/templates/base/task.html
<a href="{% url 'base:tasks' %}">Go Back</a>
<h1>Task: {{ task.title }}</h1>

base/templates/base/task_confirm_delete.html
{% extends 'base/main.html' %}
{% block content %}
<div class="header-bar">
    <a href="{% url 'base:tasks' %}">&#8592; Back</a>
</div>
<div class="card-body">
<form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to Delete this Task</p>
    <input class="button" type="submit" value="Delete">
</form>
</div>
{% endblock %}

base/templates/base/task_form.html
{% extends 'base/main.html' %}
{% block content %}
<div class="header-bar">
    <a href="{% url 'base:tasks' %}">&#8592; Back</a>
</div>

<div class="card-body">
<form method="POST" action="">
    {% csrf_token %}
    {{form.as_p}}
    <input class="button" type="submit" value="Submit">
</form>
</div>
{% endblock %}

base/templates/base/task_list.html
{% extends 'base/main.html' %}
{% block content %}
<div class="header-bar">
    <div>
        <h1>Hello, {{request.user|title}}</h1>
        <h3>You have <i>{{count}}</i> incomplete task{{count|pluralize:"s"}}</h3>
    </div>
    {% if request.user.is_authenticated %}
    <a class="btn" href="{% url 'base:logout' %}">Logout</a>
    {% else %}
    <a class="btn" href="{% url 'base:login' %}">Login</a>
    {% endif %}
</div>

<div id="search-add-wrapper">
    <form method="GET" style="margin-top: 20px; display: flex;">
        <input class="search-area" type="text" name="search-area">
        <input class="button" type="submit" value="Search">
    </form>
    <a id="add-link" href="{% url 'base:task-create' %}">&#x2b;</a>
</div>


<div class="task-items-wrapper">
    {% for task in tasks %}
        <div class="task-wrapper">
            {% if task.complete %}
                <div class="task-title">
                    <div class="task-complete-icon"></div>
                    <i><s><a href="{% url 'base:task-update' task.id %}">{{task.title}}</a></s></i>
                </div>
                <a class="delete-link" href="{% url 'base:task-delete' task.id %}">&#215;</a>
                {% else %}
                    <div class="task-title">
                        <div class="task-incomplete-icon"></div>
                        <a href="{% url 'base:task-update' task.id %}">{{task.title}}</a>
                    </div>
                    <a class="delete-link" href="{% url 'base:task-delete' task.id %}">&#215;</a>
                {% endif %}
        </div>
    {% empty %}
    <h1>No Items in the List</h1>
    {% endfor %}
</div>

{% endblock %}